---
- hosts: all
  become: yes
  tasks:
  - name: "Update repositories cache"
    apt:
      update_cache: yes

  - name: "Installing handy tools via package manager"
    ignore_errors: 'yes'
    apt:
      name: "{{ packages }}"
    vars:
      packages:
      - fish
      - python3
      - python3-pip
      - git
      - terminator
      - alacarte
      - htop
      - virtualbox-guest-x11
      - exiftool
      - rpcbind
      - rinetd
      - jq
      - awscli
      - sharutils
      - keepass2

  - name: "Installing Python3 Packages"
    shell: pip3 install pyinstaller pipreqs truffleHog
    #pip3:
      #name:
      #- pyinstaller
      #- pipreqs
      #- truffleHog

  # ==========================================================#
  # Nmap Scripts:
  # ==========================================================#
  - name: "Download nmap banner-plus.nse"
    get_url:
      url: https://raw.githubusercontent.com/grimmvenom/infosec/master/Scripts/nmap_scripts/banner-plus.nse
      dest: /usr/share/nmap/scripts/banner-plus.nse
      # mode: '0440'

  - name: "Download nmap ms15-034.nse"
    get_url:
      url: https://raw.githubusercontent.com/grimmvenom/infosec/master/Scripts/nmap_scripts/ms15-034.nse
      dest: /usr/share/nmap/scripts/ms15-034.nse
      # mode: '0440'

  - name: "Download nmap vmware-fingerprint.nse"
    get_url:
      url: https://raw.githubusercontent.com/grimmvenom/infosec/master/Scripts/nmap_scripts/vmware-fingerprint.nse
      dest: /usr/share/nmap/scripts/vmware-fingerprint.nse
      # mode: '0440'

  # ==========================================================#
  # Documentation:
  # ==========================================================#
  # Download OWASP ASVS Documentation:
  - name: "Download ASVS Documentation"
    git:
      repo: https://github.com/OWASP/ASVS
      dest: /root/Documents/OWASP-ASVS

  # Download Cheatsheets / Notes:
  - name: "Download Awesome-Pentest-Cheat-Sheets"
    git:
      repo:  https://github.com/coreb1t/awesome-pentest-cheat-sheets
      dest: /root/Documents/cheatsheets/
  # Download Wordlists
  - name: "Download SecLists Wordlists"
    git:
      repo: https://github.com/danielmiessler/SecLists
      dest: /usr/share/wordlists/SecLists
  - name: "Download Awesome-Fuzzing Wordlists"
    git:
      repo:  https://github.com/secfigo/Awesome-Fuzzing
      dest: /usr/share/wordlists/Awesome-Fuzzing
  - name: "Download Awesome-Hacking Wordlists"
    git:
      repo: https://github.com/Hack-with-Github/Awesome-Hacking
      dest: /usr/share/wordlists/Awesome-Hacking

  # ==========================================================#
  # Recon / Enumeration Tools:
  # ==========================================================#

  # Arachni Scanner:  https://github.com/Arachni/arachni/releases/download/v1.5.1/arachni-1.5.1-0.5.12-linux-x86_64.tar.gz

  - name: "Download EyeWitness: https://github.com/FortyNorthSecurity/EyeWitness"
    git:
      repo: https://github.com/FortyNorthSecurity/EyeWitness
      dest: /opt/EyeWitness

  - name: "Download WhatWeb:  https://github.com/urbanadventurer/WhatWeb.git"
    git:
      repo: https://github.com/urbanadventurer/WhatWeb
      dest: /opt/WhatWeb

  - name: "Download Responder: https://github.com/lgandx/Responder.git"
    git:
      repo: https://github.com/lgandx/Responder
      dest: /opt/Responder

  - name: "Discover: https://github.com/leebaird/discover"
    git:
      repo: https://github.com/leebaird/discover
      dest: /opt/Discover

  - name: "Download Sublist3r: https://github.com/aboul3la/Sublist3r"
    git:
      repo: https://github.com/aboul3la/Sublist3r.git
      dest: /opt/Sublist3r

  - name: "Download R3con1z3r: https://github.com/abdulgaphy/r3con1z3r"
    git:
      repo: https://github.com/abdulgaphy/r3con1z3r
      dest: /opt/reconizer

  - name: "Th3Inspecter: https://github.com/Moham3dRiahi/Th3inspector"
    git:
      repo: https://github.com/Moham3dRiahi/Th3inspector
      dest: /opt/Th3Inspecter

  - name: "Download Photon: https://github.com/s0md3v/Photon"
    git:
      repo: https://github.com/s0md3v/Photon
      dest: /opt/Photon

  - name: "Download DNSRecon: https://github.com/darkoperator/dnsrecon"
    git:
      repo: https://github.com/darkoperator/dnsrecon
      dest: /opt/dnsrecon

  - name: "Download Impacket: https://github.com/CoreSecurity/impacket.git"
    git:
      repo: https://github.com/CoreSecurity/impacket
      dest: /opt/impacket

  - name: "Download BloodHound: https://github.com/BloodHoundAD/BloodHound"
    git:
      repo: https://github.com/BloodHoundAD/BloodHound
      dest: /opt/BloodHound

  - name: "Download RedTeam Scripts: https://github.com/threatexpress/red-team-scripts"
    git:
      repo: https://github.com/threatexpress/red-team-scripts
      dest: /opt/RedTeamScripts

  # ==========================================================#
  # Powershell Exploit via Kali:
  # ==========================================================#
  - name: "Download PSEmpire: https://github.com/EmpireProject/Empire"
    git:
      repo: https://github.com/EmpireProject/Empire
      dest: /opt/PowerShell/Empire

  - name: "Download PowerSploit: https://github.com/PowerShellMafia/PowerSploit/"
    git:
      repo: https://github.com/PowerShellMafia/PowerSploit
      dest: /opt/PowerShell/PowerSploit

  - name: "Download PS DeathStar: https://github.com/byt3bl33d3r/DeathStar"
    git:
      repo: https://github.com/byt3bl33d3r/DeathStar
      dest: /opt/PowerShell/DeathStar

  # ==========================================================#
  # Social Engineering / Phishing Tools
  # ==========================================================#
  # Phishery: https://github.com/ryhanson/phishery
  #- git:
  #    repo: https://github.com/ryhanson/phishery
  #    dest: /opt/
